"""
Detailed Calorie Database with food variations and ingredients
"""

CALORIE_DATABASE = {
    "apple_pie": {
        "base_calories": 320,
        "per_serving": "1 slice (1/8 of 9-inch pie)",
        "variations": {
            "classic": {"calories": 320, "description": "Traditional apple pie with butter crust"},
            "with_vanilla_ice_cream": {"calories": 470, "description": "Apple pie à la mode"},
            "with_cheddar": {"calories": 410, "description": "Apple pie with cheddar cheese"},
            "dutch_style": {"calories": 350, "description": "Apple pie with crumb topping"},
            "sugar_free": {"calories": 280, "description": "Sugar-free apple pie"},
        },
        "ingredients": {
            "apples": {"calories": 95, "portion": "1 cup sliced"},
            "pie_crust": {"calories": 180, "portion": "1/8 crust"},
            "sugar": {"calories": 48, "portion": "2 tbsp"},
            "butter": {"calories": 102, "portion": "1 tbsp"},
        },
        "nutrition_per_100g": {"calories": 237, "protein": 1.9, "carbs": 35, "fat": 10}
    },
    
    "pizza": {
        "base_calories": 285,
        "per_serving": "1 slice (1/8 of 14-inch pizza)",
        "variations": {
            "cheese": {"calories": 285, "description": "Classic cheese pizza with tomato sauce"},
            "pepperoni": {"calories": 340, "description": "Pizza with pepperoni slices"},
            "mushroom": {"calories": 270, "description": "Pizza with mushrooms and cheese"},
            "supreme": {"calories": 380, "description": "Pizza with pepperoni, sausage, peppers, onions, mushrooms"},
            "meat_lovers": {"calories": 420, "description": "Pizza with pepperoni, sausage, bacon, ham"},
            "veggie": {"calories": 250, "description": "Pizza with assorted vegetables"},
            "margherita": {"calories": 260, "description": "Fresh mozzarella, basil, and tomato sauce"},
            "hawaiian": {"calories": 310, "description": "Pizza with ham and pineapple"},
            "bbq_chicken": {"calories": 330, "description": "BBQ sauce with grilled chicken"},
            "buffalo_chicken": {"calories": 320, "description": "Buffalo sauce with chicken and ranch"},
            "four_cheese": {"calories": 320, "description": "Mozzarella, cheddar, parmesan, feta"},
            "deep_dish": {"calories": 450, "description": "Chicago-style deep dish pizza"},
            "thin_crust": {"calories": 220, "description": "Thin and crispy crust pizza"},
            "stuffed_crust": {"calories": 360, "description": "Pizza with cheese-filled crust"},
        },
        "ingredients": {
            "pizza_crust": {"calories": 140, "portion": "1 slice base"},
            "tomato_sauce": {"calories": 20, "portion": "2 tbsp"},
            "mozzarella_cheese": {"calories": 85, "portion": "1 oz"},
            "pepperoni": {"calories": 55, "portion": "5 slices"},
            "mushrooms": {"calories": 5, "portion": "1/4 cup"},
            "sausage": {"calories": 95, "portion": "1.5 oz"},
            "bacon": {"calories": 43, "portion": "1 strip"},
            "ham": {"calories": 35, "portion": "1 oz"},
            "pineapple": {"calories": 20, "portion": "2 rings"},
            "bell_peppers": {"calories": 8, "portion": "1/4 cup"},
            "onions": {"calories": 10, "portion": "2 tbsp"},
            "olives": {"calories": 25, "portion": "5 olives"},
            "chicken": {"calories": 45, "portion": "1.5 oz"},
            "extra_cheese": {"calories": 110, "portion": "1.5 oz"},
        },
        "nutrition_per_100g": {"calories": 266, "protein": 11, "carbs": 33, "fat": 10}
    },
    
    "hamburger": {
        "base_calories": 540,
        "per_serving": "1 burger with bun",
        "variations": {
            "classic": {"calories": 540, "description": "Beef patty with lettuce, tomato, onion, pickles"},
            "cheeseburger": {"calories": 650, "description": "Classic burger with cheese"},
            "bacon_cheeseburger": {"calories": 780, "description": "Cheeseburger with bacon"},
            "double_patty": {"calories": 850, "description": "Double beef patties with cheese"},
            "mushroom_swiss": {"calories": 720, "description": "Burger with mushrooms and swiss cheese"},
            "bbq_bacon": {"calories": 750, "description": "Burger with BBQ sauce and bacon"},
            "avocado": {"calories": 680, "description": "Burger with avocado slices"},
            "egg": {"calories": 720, "description": "Burger with fried egg on top"},
            "jalapeno": {"calories": 620, "description": "Spicy burger with jalapeños"},
            "western": {"calories": 700, "description": "Burger with onion rings and BBQ sauce"},
            "turkey": {"calories": 480, "description": "Turkey patty burger"},
            "veggie": {"calories": 420, "description": "Vegetarian/Plant-based patty"},
            "slider": {"calories": 220, "description": "Mini hamburger"},
        },
        "ingredients": {
            "beef_patty": {"calories": 250, "portion": "4 oz patty"},
            "bun": {"calories": 150, "portion": "1 bun"},
            "american_cheese": {"calories": 70, "portion": "1 slice"},
            "cheddar_cheese": {"calories": 110, "portion": "1 oz"},
            "swiss_cheese": {"calories": 110, "portion": "1 oz"},
            "bacon": {"calories": 130, "portion": "2 strips"},
            "lettuce": {"calories": 2, "portion": "1 leaf"},
            "tomato": {"calories": 5, "portion": "2 slices"},
            "onion": {"calories": 10, "portion": "2 rings"},
            "pickles": {"calories": 5, "portion": "3 slices"},
            "ketchup": {"calories": 20, "portion": "1 tbsp"},
            "mayonnaise": {"calories": 50, "portion": "1 tbsp"},
            "mustard": {"calories": 5, "portion": "1 tsp"},
            "bbq_sauce": {"calories": 50, "portion": "2 tbsp"},
            "avocado": {"calories": 80, "portion": "1/4 avocado"},
            "fried_egg": {"calories": 90, "portion": "1 egg"},
            "mushrooms": {"calories": 10, "portion": "1/4 cup"},
            "jalapenos": {"calories": 5, "portion": "3 slices"},
            "onion_rings": {"calories": 150, "portion": "2 rings"},
        },
        "nutrition_per_100g": {"calories": 295, "protein": 17, "carbs": 30, "fat": 14}
    },
    
    "sushi": {
        "base_calories": 45,
        "per_serving": "1 piece nigiri / 1 roll",
        "variations": {
            "salmon_nigiri": {"calories": 55, "description": "Salmon on rice (1 piece)"},
            "tuna_nigiri": {"calories": 50, "description": "Tuna on rice (1 piece)"},
            "shrimp_nigiri": {"calories": 45, "description": "Cooked shrimp on rice (1 piece)"},
            "eel_nigiri": {"calories": 80, "description": "Grilled eel with sauce (1 piece)"},
            "tamago_nigiri": {"calories": 65, "description": "Sweet egg omelet on rice (1 piece)"},
            "california_roll": {"calories": 255, "description": "Crab, avocado, cucumber (6 pieces)"},
            "salmon_roll": {"calories": 190, "description": "Salmon and rice roll (6 pieces)"},
            "tuna_roll": {"calories": 185, "description": "Tuna and rice roll (6 pieces)"},
            "spicy_tuna_roll": {"calories": 210, "description": "Spicy tuna with mayo (6 pieces)"},
            "dragon_roll": {"calories": 320, "description": "Eel and avocado topped roll (6 pieces)"},
            "tempura_roll": {"calories": 340, "description": "Fried shrimp tempura roll (6 pieces)"},
            "philadelphia_roll": {"calories": 310, "description": "Salmon and cream cheese roll (6 pieces)"},
            "spider_roll": {"calories": 350, "description": "Soft shell crab tempura roll (6 pieces)"},
            "rainbow_roll": {"calories": 330, "description": "California roll with assorted fish on top (6 pieces)"},
            "vegetable_roll": {"calories": 160, "description": "Cucumber, avocado, carrot roll (6 pieces)"},
            "maki_cucumber": {"calories": 130, "description": "Cucumber roll (6 pieces)"},
            "maki_avocado": {"calories": 140, "description": "Avocado roll (6 pieces)"},
        },
        "ingredients": {
            "sushi_rice": {"calories": 35, "portion": "1 oz"},
            "salmon": {"calories": 40, "portion": "1 oz"},
            "tuna": {"calories": 35, "portion": "1 oz"},
            "shrimp": {"calories": 28, "portion": "1 oz"},
            "eel": {"calories": 65, "portion": "1 oz"},
            "crab_meat": {"calories": 30, "portion": "1 oz"},
            "avocado": {"calories": 45, "portion": "1/4 avocado"},
            "cucumber": {"calories": 4, "portion": "few slices"},
            "cream_cheese": {"calories": 50, "portion": "1 oz"},
            "tempura_batter": {"calories": 80, "portion": "fried coating"},
            "nori": {"calories": 5, "portion": "1 sheet"},
            "tamago": {"calories": 40, "portion": "1 piece"},
            "sesame_seeds": {"calories": 15, "portion": "1 tsp"},
            "sushi_ginger": {"calories": 5, "portion": "1 oz"},
            "wasabi": {"calories": 10, "portion": "1 tsp"},
            "soy_sauce": {"calories": 10, "portion": "1 tbsp"},
        },
        "nutrition_per_100g": {"calories": 143, "protein": 5, "carbs": 28, "fat": 1.5}
    },
    
    "pasta": {
        "base_calories": 220,
        "per_serving": "1 cup cooked pasta",
        "variations": {
            "spaghetti_bolognese": {"calories": 450, "description": "Spaghetti with meat sauce"},
            "spaghetti_carbonara": {"calories": 540, "description": "Pasta with eggs, cheese, bacon"},
            "lasagna": {"calories": 380, "description": "Layered pasta with meat and cheese (per piece)"},
            "fettuccine_alfredo": {"calories": 600, "description": "Pasta with creamy alfredo sauce"},
            "penne_arrabbiata": {"calories": 380, "description": "Pasta with spicy tomato sauce"},
            "penne_alla_vodka": {"calories": 520, "description": "Pasta with creamy tomato vodka sauce"},
            "pesto_pasta": {"calories": 480, "description": "Pasta with basil pesto sauce"},
            "macaroni_cheese": {"calories": 380, "description": "Macaroni with cheese sauce (1 cup)"},
            "baked_ziti": {"calories": 420, "description": "Baked pasta with cheese and sauce"},
            "ravioli_cheese": {"calories": 340, "description": "Cheese-filled pasta (5-6 pieces)"},
            "ravioli_meat": {"calories": 390, "description": "Meat-filled pasta (5-6 pieces)"},
            "gnocchi": {"calories": 290, "description": "Potato dumplings (1 cup)"},
            "ravioli_spinach": {"calories": 320, "description": "Spinach and ricotta ravioli (5-6 pieces)"},
            "linguine_clam": {"calories": 410, "description": "Pasta with clams in white wine sauce"},
            "shrimp_scampi": {"calories": 460, "description": "Pasta with shrimp in garlic butter"},
            "pasta_primavera": {"calories": 340, "description": "Pasta with fresh vegetables"},
            "pasta_marinara": {"calories": 280, "description": "Pasta with tomato marinara sauce"},
        },
        "ingredients": {
            "pasta_cooked": {"calories": 220, "portion": "1 cup"},
            "ground_beef": {"calories": 180, "portion": "3 oz"},
            "italian_sausage": {"calories": 260, "portion": "3 oz"},
            "marinara_sauce": {"calories": 70, "portion": "1/2 cup"},
            "alfredo_sauce": {"calories": 280, "portion": "1/2 cup"},
            "pesto_sauce": {"calories": 230, "portion": "1/4 cup"},
            "parmesan_cheese": {"calories": 110, "portion": "1 oz"},
            "mozzarella_cheese": {"calories": 85, "portion": "1 oz"},
            "ricotta_cheese": {"calories": 100, "portion": "1/2 cup"},
            "heavy_cream": {"calories": 200, "portion": "1/4 cup"},
            "olive_oil": {"calories": 120, "portion": "1 tbsp"},
            "butter": {"calories": 100, "portion": "1 tbsp"},
            "egg": {"calories": 70, "portion": "1 large"},
            "bacon": {"calories": 130, "portion": "2 strips"},
            "shrimp": {"calories": 85, "portion": "3 oz"},
            "chicken": {"calories": 140, "portion": "3 oz"},
            "mushrooms": {"calories": 20, "portion": "1/2 cup"},
            "spinach": {"calories": 15, "portion": "1 cup"},
            "tomatoes": {"calories": 25, "portion": "1/2 cup"},
            "onions": {"calories": 30, "portion": "1/2 cup"},
            "garlic": {"calories": 10, "portion": "2 cloves"},
        },
        "nutrition_per_100g": {"calories": 131, "protein": 5, "carbs": 25, "fat": 1.5}
    },
    
    "salad": {
        "base_calories": 35,
        "per_serving": "2 cups mixed greens",
        "variations": {
            "caesar_salad": {"calories": 350, "description": "Romaine with caesar dressing and croutons"},
            "greek_salad": {"calories": 290, "description": "Cucumber, tomato, olives, feta with dressing"},
            "caprese_salad": {"calories": 280, "description": "Tomato, mozzarella, basil with olive oil"},
            "cobb_salad": {"calories": 620, "description": "Greens with chicken, bacon, egg, avocado, cheese"},
            "chef_salad": {"calories": 450, "description": "Greens with ham, turkey, cheese, egg"},
            "garden_salad": {"calories": 120, "description": "Mixed greens with vegetables, light dressing"},
            "spinach_salad": {"calories": 180, "description": "Spinach with bacon, egg, mushrooms"},
            "beet_salad": {"calories": 220, "description": "Beets with goat cheese and walnuts"},
            "waldorf_salad": {"calories": 310, "description": "Apples, celery, walnuts with mayo dressing"},
            "pasta_salad": {"calories": 380, "description": "Pasta with vegetables and dressing"},
            "potato_salad": {"calories": 350, "description": "Potatoes with mayo dressing"},
            "coleslaw": {"calories": 180, "description": "Cabbage with creamy dressing"},
            "taco_salad": {"calories": 580, "description": "Seasoned beef, beans, cheese, chips"},
            "asian_chicken_salad": {"calories": 420, "description": "Chicken with mandarin oranges, almonds, sesame dressing"},
            "southwest_salad": {"calories": 380, "description": "Chicken, corn, beans, tortilla strips"},
            "nicoise_salad": {"calories": 340, "description": "Tuna, eggs, potatoes, green beans"},
        },
        "ingredients": {
            "mixed_greens": {"calories": 20, "portion": "2 cups"},
            "romaine_lettuce": {"calories": 16, "portion": "2 cups"},
            "spinach": {"calories": 14, "portion": "2 cups"},
            "tomato": {"calories": 22, "portion": "1 medium"},
            "cucumber": {"calories": 16, "portion": "1 cup sliced"},
            "carrots": {"calories": 25, "portion": "1/2 cup"},
            "bell_peppers": {"calories": 24, "portion": "1 cup"},
            "red_onion": {"calories": 24, "portion": "1/2 cup"},
            "avocado": {"calories": 120, "portion": "1/2 avocado"},
            "grilled_chicken": {"calories": 140, "portion": "3 oz"},
            "bacon_bits": {"calories": 60, "portion": "2 tbsp"},
            "hard_boiled_egg": {"calories": 70, "portion": "1 egg"},
            "croutons": {"calories": 60, "portion": "1/2 cup"},
            "parmesan_cheese": {"calories": 55, "portion": "1/4 cup"},
            "feta_cheese": {"calories": 75, "portion": "1 oz"},
            "cheddar_cheese": {"calories": 110, "portion": "1 oz"},
            "goat_cheese": {"calories": 75, "portion": "1 oz"},
            "olives": {"calories": 45, "portion": "5 olives"},
            "walnuts": {"calories": 100, "portion": "1 oz"},
            "almonds": {"calories": 100, "portion": "1 oz"},
            "sunflower_seeds": {"calories": 85, "portion": "1 oz"},
            "caesar_dressing": {"calories": 160, "portion": "2 tbsp"},
            "ranch_dressing": {"calories": 140, "portion": "2 tbsp"},
            "italian_dressing": {"calories": 80, "portion": "2 tbsp"},
            "balsamic_vinaigrette": {"calories": 90, "portion": "2 tbsp"},
            "olive_oil": {"calories": 120, "portion": "1 tbsp"},
        },
        "nutrition_per_100g": {"calories": 33, "protein": 2, "carbs": 5, "fat": 0.5}
    },
    
    "desserts": {
        "base_calories": 300,
        "per_serving": "1 serving",
        "variations": {
            "cheesecake": {"calories": 400, "description": "Classic New York style cheesecake (1 slice)"},
            "chocolate_cake": {"calories": 350, "description": "Chocolate layer cake with frosting (1 slice)"},
            "carrot_cake": {"calories": 380, "description": "Carrot cake with cream cheese frosting (1 slice)"},
            "red_velvet_cake": {"calories": 360, "description": "Red velvet with cream cheese frosting (1 slice)"},
            "tiramisu": {"calories": 340, "description": "Coffee-flavored Italian dessert (1 piece)"},
            "chocolate_mousse": {"calories": 280, "description": "Light chocolate mousse (1 cup)"},
            "creme_brulee": {"calories": 310, "description": "Custard with caramelized sugar top (1 ramekin)"},
            "panna_cotta": {"calories": 240, "description": "Italian cream custard (1 serving)"},
            "ice_cream": {"calories": 270, "description": "Vanilla ice cream (1 cup)"},
            "chocolate_ice_cream": {"calories": 285, "description": "Chocolate ice cream (1 cup)"},
            "strawberry_shortcake": {"calories": 330, "description": "Biscuit with strawberries and cream (1 piece)"},
            "bread_pudding": {"calories": 320, "description": "Baked bread custard dessert (1 cup)"},
            "churros": {"calories": 280, "description": "Fried dough with cinnamon sugar (2 pieces)"},
            "donuts": {"calories": 250, "description": "Glazed yeast donut (1 piece)"},
            "chocolate_donut": {"calories": 320, "description": "Chocolate glazed donut (1 piece)"},
            "cupcakes": {"calories": 290, "description": "Vanilla cupcake with frosting (1 piece)"},
            "cannoli": {"calories": 260, "description": "Italian pastry with ricotta filling (1 piece)"},
            "macarons": {"calories": 70, "description": "French almond meringue cookies (1 piece)"},
            "baklava": {"calories": 330, "description": "Phyllo pastry with nuts and honey (1 piece)"},
            "frozen_yogurt": {"calories": 220, "description": "Frozen yogurt (1 cup)"},
        },
        "ingredients": {
            "flour": {"calories": 455, "portion": "1 cup"},
            "sugar": {"calories": 774, "portion": "1 cup"},
            "butter": {"calories": 810, "portion": "1/2 cup"},
            "eggs": {"calories": 70, "portion": "1 large"},
            "cream_cheese": {"calories": 800, "portion": "8 oz"},
            "heavy_cream": {"calories": 400, "portion": "1/2 cup"},
            "chocolate": {"calories": 150, "portion": "1 oz"},
            "cocoa_powder": {"calories": 50, "portion": "2 tbsp"},
            "vanilla_extract": {"calories": 12, "portion": "1 tsp"},
            "ice_cream_base": {"calories": 270, "portion": "1 cup"},
        },
        "nutrition_per_100g": {"calories": 360, "protein": 4, "carbs": 50, "fat": 16}
    },
    
    "asian_cuisine": {
        "base_calories": 400,
        "per_serving": "1 serving",
        "variations": {
            "chicken_curry": {"calories": 420, "description": "Chicken in curry sauce with rice (1 cup)"},
            "pad_thai": {"calories": 450, "description": "Stir-fried rice noodles with shrimp/tofu (1 plate)"},
            "fried_rice": {"calories": 380, "description": "Stir-fried rice with vegetables and egg (1 cup)"},
            "ramen": {"calories": 480, "description": "Japanese noodle soup with broth and toppings"},
            "pho": {"calories": 420, "description": "Vietnamese noodle soup with beef (1 bowl)"},
            "bibimbap": {"calories": 520, "description": "Korean rice bowl with vegetables and meat"},
            "gyoza": {"calories": 280, "description": "Pan-fried dumplings (6 pieces)"},
            "dumplings": {"calories": 240, "description": "Steamed dumplings (6 pieces)"},
            "spring_rolls": {"calories": 140, "description": "Fresh rice paper rolls (2 pieces)"},
            "egg_rolls": {"calories": 220, "description": "Fried spring rolls (2 pieces)"},
            "samosa": {"calories": 160, "description": "Fried Indian pastry (2 pieces)"},
            "takoyaki": {"calories": 180, "description": "Octopus balls (4 pieces)"},
            "tempura": {"calories": 320, "description": "Battered and fried seafood/vegetables (5 pieces)"},
            "miso_soup": {"calories": 80, "description": "Soybean paste soup with tofu (1 cup)"},
            "edamame": {"calories": 120, "description": "Steamed soybeans (1 cup)"},
            "hot_and_sour_soup": {"calories": 120, "description": "Chinese soup with tofu and mushrooms (1 cup)"},
        },
        "ingredients": {
            "white_rice": {"calories": 200, "portion": "1 cup cooked"},
            "rice_noodles": {"calories": 192, "portion": "1 cup cooked"},
            "ramen_noodles": {"calories": 190, "portion": "1 cup"},
            "rice_paper": {"calories": 30, "portion": "1 sheet"},
            "tofu": {"calories": 90, "portion": "4 oz"},
            "chicken": {"calories": 165, "portion": "4 oz"},
            "shrimp": {"calories": 100, "portion": "4 oz"},
            "pork": {"calories": 220, "portion": "4 oz"},
            "beef": {"calories": 250, "portion": "4 oz"},
            "egg": {"calories": 70, "portion": "1 large"},
            "peanuts": {"calories": 160, "portion": "1 oz"},
            "cashews": {"calories": 160, "portion": "1 oz"},
            "coconut_milk": {"calories": 120, "portion": "1/3 cup"},
            "curry_paste": {"calories": 45, "portion": "2 tbsp"},
            "soy_sauce": {"calories": 15, "portion": "2 tbsp"},
            "fish_sauce": {"calories": 10, "portion": "2 tbsp"},
            "sesame_oil": {"calories": 120, "portion": "1 tbsp"},
            "vegetable_oil": {"calories": 120, "portion": "1 tbsp"},
        },
        "nutrition_per_100g": {"calories": 150, "protein": 6, "carbs": 20, "fat": 6}
    },
    
    "breakfast": {
        "base_calories": 450,
        "per_serving": "1 serving",
        "variations": {
            "pancakes": {"calories": 520, "description": "3 pancakes with butter and syrup"},
            "french_toast": {"calories": 480, "description": "3 slices with butter and syrup"},
            "waffles": {"calories": 410, "description": "2 waffles with butter and syrup"},
            "eggs_benedict": {"calories": 560, "description": "English muffin with poached eggs and hollandaise"},
            "huevos_rancheros": {"calories": 450, "description": "Eggs with salsa on tortillas"},
            "omelette": {"calories": 380, "description": "3-egg omelette with cheese and vegetables"},
            "breakfast_burrito": {"calories": 580, "description": "Flour tortilla with eggs, cheese, meat, potatoes"},
            "scrambled_eggs": {"calories": 280, "description": "2 eggs with butter (no sides)"},
            "fried_eggs": {"calories": 180, "description": "2 fried eggs"},
            "bacon_and_eggs": {"calories": 420, "description": "2 eggs with 4 strips bacon"},
            "sausage_and_eggs": {"calories": 580, "description": "2 eggs with 2 sausage links"},
            "hash_browns": {"calories": 210, "description": "1 cup hash browns"},
            "home_fries": {"calories": 280, "description": "1 cup home fries"},
            "breakfast_sandwich": {"calories": 450, "description": "English muffin with egg, cheese, meat"},
            "croque_madame": {"calories": 620, "description": "Ham and cheese sandwich with egg on top"},
            "bagel_with_cream_cheese": {"calories": 380, "description": "Plain bagel with cream cheese"},
            "oatmeal": {"calories": 150, "description": "1 cup cooked oatmeal with milk"},
            "granola": {"calories": 240, "description": "1/2 cup granola with milk"},
        },
        "ingredients": {
            "eggs": {"calories": 70, "portion": "1 large"},
            "bacon": {"calories": 130, "portion": "2 strips"},
            "sausage": {"calories": 260, "portion": "2 links"},
            "ham": {"calories": 60, "portion": "2 oz"},
            "cheddar_cheese": {"calories": 110, "portion": "1 oz"},
            "american_cheese": {"calories": 70, "portion": "1 slice"},
            "pancakes": {"calories": 90, "portion": "1 pancake"},
            "waffles": {"calories": 120, "portion": "1 waffle"},
            "french_toast": {"calories": 130, "portion": "1 slice"},
            "syrup": {"calories": 100, "portion": "2 tbsp"},
            "butter": {"calories": 100, "portion": "1 tbsp"},
            "english_muffin": {"calories": 130, "portion": "1 muffin"},
            "flour_tortilla": {"calories": 140, "portion": "1 medium"},
            "hash_browns": {"calories": 210, "portion": "1 cup"},
            "home_fries": {"calories": 280, "portion": "1 cup"},
            "potatoes": {"calories": 110, "portion": "1 medium"},
            "bagel": {"calories": 250, "portion": "1 medium"},
            "cream_cheese": {"calories": 100, "portion": "2 tbsp"},
            "oatmeal_dry": {"calories": 150, "portion": "1/2 cup"},
            "milk": {"calories": 80, "portion": "1/2 cup"},
            "hollandaise_sauce": {"calories": 150, "portion": "1/4 cup"},
        },
        "nutrition_per_100g": {"calories": 180, "protein": 10, "carbs": 15, "fat": 10}
    },
    
    "mexican_cuisine": {
        "base_calories": 350,
        "per_serving": "1 serving",
        "variations": {
            "tacos": {"calories": 280, "description": "2 corn tortilla tacos with meat and toppings"},
            "burrito": {"calories": 550, "description": "Flour tortilla with rice, beans, meat, cheese"},
            "quesadilla": {"calories": 480, "description": "Flour tortilla with cheese and meat (1 large)"},
            "chicken_quesadilla": {"calories": 520, "description": "Quesadilla with grilled chicken"},
            "nachos": {"calories": 680, "description": "Tortilla chips with cheese, beans, meat, toppings"},
            "enchiladas": {"calories": 420, "description": "2 corn tortillas with meat, cheese, sauce"},
            "fajitas": {"calories": 380, "description": "Grilled meat with peppers, onions, tortillas"},
            "tostadas": {"calories": 320, "description": "2 crispy tortillas with beans, meat, toppings"},
            "chimichanga": {"calories": 620, "description": "Deep-fried burrito"},
            "taquitos": {"calories": 340, "description": "4 rolled fried tacos"},
            "flautas": {"calories": 350, "description": "4 rolled fried tortillas with chicken"},
            "taco_salad": {"calories": 580, "description": "Taco shell bowl with meat, beans, cheese"},
            "chile_relleno": {"calories": 480, "description": "Stuffed pepper with cheese, battered and fried"},
            "guacamole": {"calories": 100, "description": "1/2 cup guacamole with chips (chips separate)"},
            "salsa": {"calories": 20, "description": "1/2 cup salsa"},
            "refried_beans": {"calories": 240, "description": "1 cup refried beans"},
            "mexican_rice": {"calories": 220, "description": "1 cup Mexican rice"},
        },
        "ingredients": {
            "corn_tortilla": {"calories": 50, "portion": "1 small"},
            "flour_tortilla": {"calories": 140, "portion": "1 medium"},
            "taco_shell": {"calories": 70, "portion": "1 shell"},
            "ground_beef": {"calories": 180, "portion": "3 oz"},
            "shredded_chicken": {"calories": 140, "portion": "3 oz"},
            "carnitas": {"calories": 200, "portion": "3 oz"},
            "carne_asada": {"calories": 190, "portion": "3 oz"},
            "cheddar_cheese": {"calories": 110, "portion": "1 oz"},
            "queso_fresco": {"calories": 90, "portion": "1 oz"},
            "sour_cream": {"calories": 60, "portion": "2 tbsp"},
            "guacamole": {"calories": 100, "portion": "1/2 cup"},
            "salsa": {"calories": 20, "portion": "1/2 cup"},
            "refried_beans": {"calories": 240, "portion": "1 cup"},
            "black_beans": {"calories": 220, "portion": "1 cup"},
            "mexican_rice": {"calories": 220, "portion": "1 cup"},
            "lettuce": {"calories": 2, "portion": "1/4 cup"},
            "tomato": {"calories": 5, "portion": "2 tbsp"},
            "onion": {"calories": 10, "portion": "2 tbsp"},
            "jalapenos": {"calories": 5, "portion": "2 slices"},
            "cilantro": {"calories": 1, "portion": "1 tbsp"},
            "lime": {"calories": 5, "portion": "1 wedge"},
            "tortilla_chips": {"calories": 140, "portion": "1 oz (about 10 chips)"},
        },
        "nutrition_per_100g": {"calories": 200, "protein": 8, "carbs": 20, "fat": 10}
    },
    
    "sandwiches": {
        "base_calories": 450,
        "per_serving": "1 sandwich",
        "variations": {
            "club_sandwich": {"calories": 580, "description": "Triple-decker with turkey, bacon, lettuce, tomato"},
            "grilled_cheese": {"calories": 420, "description": "Bread with melted cheese, butter"},
            "turkey_sandwich": {"calories": 480, "description": "Turkey with cheese, lettuce, tomato, mayo"},
            "ham_and_cheese": {"calories": 450, "description": "Ham and cheese with lettuce, tomato"},
            "roast_beef": {"calories": 520, "description": "Roast beef with cheese and horseradish"},
            "blt": {"calories": 380, "description": "Bacon, lettuce, tomato sandwich"},
            "pb_and_j": {"calories": 380, "description": "Peanut butter and jelly sandwich"},
            "tuna_salad": {"calories": 450, "description": "Tuna salad with mayo on bread"},
            "chicken_salad": {"calories": 480, "description": "Chicken salad sandwich"},
            "egg_salad": {"calories": 440, "description": "Egg salad sandwich"},
            "french_dip": {"calories": 620, "description": "Roast beef sandwich with au jus"},
            "meatball_sub": {"calories": 680, "description": "Meatballs with marinara on sub roll"},
            "italian_sub": {"calories": 650, "description": "Assorted meats and cheese on sub roll"},
            "lobster_roll": {"calories": 420, "description": "Lobster salad on buttered roll"},
            "crab_cake_sandwich": {"calories": 580, "description": "Crab cake on bun with tartar sauce"},
            "pulled_pork": {"calories": 550, "description": "BBQ pulled pork on bun"},
            "reuben": {"calories": 620, "description": "Corned beef, sauerkraut, swiss, russian dressing"},
            "philly_cheesesteak": {"calories": 700, "description": "Steak with cheese on hoagie roll"},
            "chicken_parmesan": {"calories": 680, "description": "Breaded chicken with marinara and cheese"},
        },
        "ingredients": {
            "white_bread": {"calories": 160, "portion": "2 slices"},
            "wheat_bread": {"calories": 140, "portion": "2 slices"},
            "sourdough": {"calories": 150, "portion": "2 slices"},
            "rye_bread": {"calories": 160, "portion": "2 slices"},
            "sub_roll": {"calories": 220, "portion": "1 roll"},
            "hamburger_bun": {"calories": 150, "portion": "1 bun"},
            "brioche_bun": {"calories": 200, "portion": "1 bun"},
            "turkey": {"calories": 90, "portion": "4 oz"},
            "ham": {"calories": 120, "portion": "4 oz"},
            "roast_beef": {"calories": 200, "portion": "4 oz"},
            "corned_beef": {"calories": 220, "portion": "4 oz"},
            "bacon": {"calories": 130, "portion": "4 strips"},
            "cheddar_cheese": {"calories": 110, "portion": "1 oz"},
            "swiss_cheese": {"calories": 110, "portion": "1 oz"},
            "american_cheese": {"calories": 70, "portion": "1 slice"},
            "provolone": {"calories": 100, "portion": "1 oz"},
            "mozzarella": {"calories": 85, "portion": "1 oz"},
            "mayonnaise": {"calories": 100, "portion": "2 tbsp"},
            "mustard": {"calories": 10, "portion": "2 tsp"},
            "ketchup": {"calories": 40, "portion": "2 tbsp"},
            "lettuce": {"calories": 5, "portion": "2 leaves"},
            "tomato": {"calories": 10, "portion": "3 slices"},
            "onion": {"calories": 15, "portion": "3 rings"},
            "pickles": {"calories": 10, "portion": "3 slices"},
            "sauerkraut": {"calories": 15, "portion": "1/4 cup"},
            "peanut_butter": {"calories": 190, "portion": "2 tbsp"},
            "jelly": {"calories": 110, "portion": "2 tbsp"},
        },
        "nutrition_per_100g": {"calories": 250, "protein": 12, "carbs": 25, "fat": 12}
    },
}

# Complete food mapping from Food-101 classes to calorie database
def get_food_mapping():
    """Map Food-101 classes to calorie database categories"""
    return {
        # Desserts
        "apple_pie": ("apple_pie", "classic"),
        "baklava": ("desserts", "baklava"),
        "cannoli": ("desserts", "cannoli"),
        "carrot_cake": ("desserts", "carrot_cake"),
        "cheesecake": ("desserts", "cheesecake"),
        "chocolate_cake": ("desserts", "chocolate_cake"),
        "chocolate_mousse": ("desserts", "chocolate_mousse"),
        "churros": ("desserts", "churros"),
        "creme_brulee": ("desserts", "creme_brulee"),
        "cup_cakes": ("desserts", "cupcakes"),
        "donuts": ("desserts", "donuts"),
        "frozen_yogurt": ("desserts", "frozen_yogurt"),
        "ice_cream": ("desserts", "ice_cream"),
        "macarons": ("desserts", "macarons"),
        "panna_cotta": ("desserts", "panna_cotta"),
        "red_velvet_cake": ("desserts", "red_velvet_cake"),
        "strawberry_shortcake": ("desserts", "strawberry_shortcake"),
        "tiramisu": ("desserts", "tiramisu"),
        "bread_pudding": ("desserts", "bread_pudding"),
        "waffles": ("breakfast", "waffles"),
        "beignets": ("desserts", "donuts"),  # Similar to donuts
        
        # Breakfast
        "breakfast_burrito": ("breakfast", "breakfast_burrito"),
        "croque_madame": ("breakfast", "croque_madame"),
        "eggs_benedict": ("breakfast", "eggs_benedict"),
        "french_toast": ("breakfast", "french_toast"),
        "huevos_rancheros": ("breakfast", "huevos_rancheros"),
        "omelette": ("breakfast", "omelette"),
        "pancakes": ("breakfast", "pancakes"),
        
        # Sandwiches
        "club_sandwich": ("sandwiches", "club_sandwich"),
        "grilled_cheese_sandwich": ("sandwiches", "grilled_cheese"),
        "hamburger": ("hamburger", "classic"),
        "hot_dog": ("hamburger", "classic"),  # Similar structure
        "lobster_roll_sandwich": ("sandwiches", "lobster_roll"),
        "pulled_pork_sandwich": ("sandwiches", "pulled_pork"),
        "crab_cakes": ("sandwiches", "crab_cake_sandwich"),
        
        # Pasta
        "gnocchi": ("pasta", "gnocchi"),
        "lasagna": ("pasta", "lasagna"),
        "macaroni_and_cheese": ("pasta", "macaroni_cheese"),
        "ramen": ("asian_cuisine", "ramen"),
        "ravioli": ("pasta", "ravioli_cheese"),
        "risotto": ("pasta", "risotto"),
        "spaghetti_bolognese": ("pasta", "spaghetti_bolognese"),
        "spaghetti_carbonara": ("pasta", "spaghetti_carbonara"),
        
        # Pizza
        "pizza": ("pizza", "cheese"),
        
        # Sushi
        "sushi": ("sushi", "salmon_nigiri"),
        "sashimi": ("sushi", "salmon_nigiri"),
        
        # Asian
        "bibimbap": ("asian_cuisine", "bibimbap"),
        "chicken_curry": ("asian_cuisine", "chicken_curry"),
        "dumplings": ("asian_cuisine", "dumplings"),
        "edamame": ("asian_cuisine", "edamame"),
        "fried_rice": ("asian_cuisine", "fried_rice"),
        "gyoza": ("asian_cuisine", "gyoza"),
        "miso_soup": ("asian_cuisine", "miso_soup"),
        "pad_thai": ("asian_cuisine", "pad_thai"),
        "pho": ("asian_cuisine", "pho"),
        "takoyaki": ("asian_cuisine", "takoyaki"),
        "tempura": ("asian_cuisine", "tempura"),
        "hot_and_sour_soup": ("asian_cuisine", "hot_and_sour_soup"),
        "spring_rolls": ("asian_cuisine", "spring_rolls"),
        "egg_rolls": ("asian_cuisine", "egg_rolls"),
        "samosa": ("asian_cuisine", "samosa"),
        
        # Mexican
        "tacos": ("mexican_cuisine", "tacos"),
        "burrito": ("mexican_cuisine", "burrito"),
        "quesadilla": ("mexican_cuisine", "quesadilla"),
        "chicken_quesadilla": ("mexican_cuisine", "chicken_quesadilla"),
        "nachos": ("mexican_cuisine", "nachos"),
        "enchiladas": ("mexican_cuisine", "enchiladas"),
        "fajitas": ("mexican_cuisine", "fajitas"),
        "chimichanga": ("mexican_cuisine", "chimichanga"),
        "taquitos": ("mexican_cuisine", "taquitos"),
        "taco_salad": ("mexican_cuisine", "taco_salad"),
        "chile_relleno": ("mexican_cuisine", "chile_relleno"),
        "guacamole": ("mexican_cuisine", "guacamole"),
        "salsa": ("mexican_cuisine", "salsa"),
        "refried_beans": ("mexican_cuisine", "refried_beans"),
        "mexican_rice": ("mexican_cuisine", "mexican_rice"),
        
        # Salads
        "caesar_salad": ("salad", "caesar_salad"),
        "greek_salad": ("salad", "greek_salad"),
        "caprese_salad": ("salad", "caprese_salad"),
        "beet_salad": ("salad", "beet_salad"),
        "seaweed_salad": ("salad", "nicoise_salad"),  # Default
        
        # Seafood
        "ceviche": ("asian_cuisine", "ceviche"),
        "clam_chowder": ("asian_cuisine", "clam_chowder"),
        "fish_and_chips": ("asian_cuisine", "fish_and_chips"),
        "grilled_salmon": ("asian_cuisine", "grilled_salmon"),
        "lobster_bisque": ("asian_cuisine", "lobster_bisque"),
        "mussels": ("asian_cuisine", "mussels"),
        "oysters": ("asian_cuisine", "oysters"),
        "scallops": ("asian_cuisine", "scallops"),
        "shrimp_and_grits": ("asian_cuisine", "shrimp_and_grits"),
        "fried_calamari": ("asian_cuisine", "fried_calamari"),
        "paella": ("asian_cuisine", "paella"),
        "lobster_roll_sandwich": ("sandwiches", "lobster_roll"),
        
        # Meat dishes
        "baby_back_ribs": ("asian_cuisine", "baby_back_ribs"),
        "beef_carpaccio": ("asian_cuisine", "beef_carpaccio"),
        "beef_tartare": ("asian_cuisine", "beef_tartare"),
        "filet_mignon": ("asian_cuisine", "filet_mignon"),
        "foie_gras": ("asian_cuisine", "foie_gras"),
        "lamb_chops": ("asian_cuisine", "lamb_chops"),
        "peking_duck": ("asian_cuisine", "peking_duck"),
        "pork_chop": ("asian_cuisine", "pork_chop"),
        "prime_rib": ("asian_cuisine", "prime_rib"),
        "steak": ("asian_cuisine", "steak"),
        "tuna_tartare": ("asian_cuisine", "tuna_tartare"),
        "chicken_wings": ("asian_cuisine", "chicken_wings"),
        
        # Appetizers & Sides
        "bruschetta": ("asian_cuisine", "bruschetta"),
        "caprese_salad": ("salad", "caprese_salad"),
        "cheese_plate": ("desserts", "cheese_plate"),
        "deviled_eggs": ("breakfast", "deviled_eggs"),
        "escargots": ("asian_cuisine", "escargots"),
        "falafel": ("asian_cuisine", "falafel"),
        "french_fries": ("asian_cuisine", "french_fries"),
        "french_onion_soup": ("asian_cuisine", "french_onion_soup"),
        "garlic_bread": ("asian_cuisine", "garlic_bread"),
        "hummus": ("asian_cuisine", "hummus"),
        "onion_rings": ("asian_cuisine", "onion_rings"),
        "poutine": ("asian_cuisine", "poutine"),
    }
